import type React from 'react';

export const S: Record<string, React.CSSProperties> = {
  // 루트
  container: {
    fontFamily: 'Söhne, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    backgroundColor: '#f5f0e8',
    color: '#2d2b28',
    minHeight: '100vh',
  },

  // 헤더
  header: {
    padding: '10px 20px',
    backgroundColor: '#ebe5db',
    borderBottom: '1px solid #ddd5c8',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    WebkitAppRegion: 'drag' as any,
  },
  headerLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    WebkitAppRegion: 'no-drag' as any,
  },
  backBtn: {
    background: 'none',
    border: 'none',
    color: '#78716c',
    cursor: 'pointer',
    padding: '4px 6px',
    borderRadius: 6,
    display: 'flex',
    alignItems: 'center',
  },
  title: {
    margin: 0,
    fontSize: 15,
    fontWeight: 600,
    color: '#1c1917',
    letterSpacing: -0.3,
  },
  pathBar: {
    display: 'flex',
    gap: 6,
    flex: 1,
    maxWidth: 520,
    WebkitAppRegion: 'no-drag' as any,
  },
  pathInput: {
    flex: 1,
    padding: '6px 10px',
    borderRadius: 8,
    border: '1px solid #d6d0c4',
    backgroundColor: '#fff',
    color: '#1c1917',
    fontSize: 12,
    outline: 'none',
  },
  btn: {
    padding: '6px 14px',
    borderRadius: 8,
    border: 'none',
    backgroundColor: '#c2703e',
    color: '#fff',
    cursor: 'pointer',
    fontSize: 12,
    fontWeight: 500,
  },
  btnGhost: {
    padding: '4px 8px',
    borderRadius: 8,
    border: '1px solid #d6d0c4',
    background: '#fff',
    color: '#78716c',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
  },
  error: {
    margin: '12px 20px',
    padding: '10px 14px',
    backgroundColor: '#fef2f2',
    border: '1px solid #fecaca',
    borderRadius: 10,
    color: '#991b1b',
    fontSize: 13,
  },
  loading: { margin: '12px 20px', color: '#a8a29e', fontSize: 13 },
  phaseBadge: {
    padding: '2px 10px',
    borderRadius: 12,
    fontSize: 11,
    fontWeight: 500,
    color: '#fff',
    letterSpacing: 0.2,
  },

  // ── 프로젝트 목록 ──
  listPage: { padding: '24px 28px' },
  emptyState: { textAlign: 'center' as const, padding: '60px 0' },
  emptyIcon: { fontSize: 32, marginBottom: 8 },
  emptyText: { color: '#a8a29e', fontSize: 14 },
  projectGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))',
    gap: 14,
  },
  projectCard: {
    backgroundColor: '#fff',
    border: '1px solid #e7e0d5',
    borderRadius: 14,
    padding: 16,
    cursor: 'pointer',
    textAlign: 'left' as const,
    color: '#2d2b28',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 10,
    transition: 'box-shadow 0.15s, border-color 0.15s',
    boxShadow: '0 1px 3px rgba(0,0,0,0.04)',
  },
  projectCardTop: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  projectName: {
    fontWeight: 600,
    fontSize: 14,
    color: '#1c1917',
    letterSpacing: -0.2,
  },
  phaseBadgeSmall: {
    padding: '2px 8px',
    borderRadius: 8,
    fontSize: 10,
    fontWeight: 500,
    color: '#fff',
    textTransform: 'capitalize' as const,
  },
  taskCount: {
    padding: '2px 8px',
    borderRadius: 8,
    fontSize: 11,
    fontWeight: 500,
    backgroundColor: '#f5f0e8',
    color: '#78716c',
  },
  cardMeta: { display: 'flex', gap: 8 },
  metaItem: { fontSize: 11, color: '#a8a29e' },
  metaLabel: {
    fontSize: 10,
    color: '#a8a29e',
    backgroundColor: '#f5f0e8',
    padding: '1px 6px',
    borderRadius: 4,
    textTransform: 'uppercase' as const,
    fontWeight: 500,
    letterSpacing: 0.5,
  },

  // ── 프로젝트 상세 ──
  detailPage: {
    display: 'flex',
    flexDirection: 'column' as const,
    height: 'calc(100vh - 45px)',
  },
  phaseTabs: {
    display: 'flex',
    gap: 0,
    backgroundColor: '#ebe5db',
    padding: '0 20px',
  },
  phaseTab: {
    padding: '10px 22px',
    background: 'none',
    border: 'none',
    borderBottom: '2px solid transparent',
    color: '#a8a29e',
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 500,
    letterSpacing: -0.1,
    transition: 'color 0.1s',
  },
  phaseTabActive: {
    color: '#1c1917',
    borderBottomColor: '#c2703e',
    fontWeight: 600,
  },
  subTabs: {
    display: 'flex',
    gap: 6,
    padding: '10px 20px',
    borderBottom: '1px solid #e7e0d5',
    backgroundColor: '#faf7f2',
  },
  subTab: {
    padding: '5px 14px',
    background: 'none',
    border: '1px solid #ddd5c8',
    borderRadius: 8,
    color: '#78716c',
    cursor: 'pointer',
    fontSize: 12,
    fontWeight: 500,
    display: 'flex',
    alignItems: 'center',
    gap: 5,
    transition: 'all 0.1s',
  },
  subTabActive: {
    backgroundColor: '#fff',
    color: '#1c1917',
    borderColor: '#c2703e',
    boxShadow: '0 1px 2px rgba(0,0,0,0.05)',
  },
  dot: {
    width: 5,
    height: 5,
    borderRadius: '50%',
    backgroundColor: '#22c55e',
    display: 'inline-block',
  },

  // ── 콘텐츠 ──
  contentArea: { display: 'flex', flex: 1, overflow: 'hidden' as const },
  fileSidebar: {
    width: 200,
    borderRight: '1px solid #e7e0d5',
    backgroundColor: '#faf7f2',
    padding: '0',
    overflowY: 'auto' as const,
  },
  sidebarHeader: {
    padding: '12px 14px 8px',
    fontSize: 11,
    fontWeight: 600,
    color: '#a8a29e',
    textTransform: 'uppercase' as const,
    letterSpacing: 0.8,
  },
  fileItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    width: '100%',
    padding: '7px 14px',
    background: 'none',
    border: 'none',
    color: '#57534e',
    cursor: 'pointer',
    fontSize: 12,
    textAlign: 'left' as const,
    transition: 'background 0.1s',
  },
  fileItemActive: {
    backgroundColor: '#fff',
    color: '#1c1917',
    fontWeight: 500,
    borderRight: '2px solid #c2703e',
  },
  fileIcon: { fontSize: 8, color: '#c2703e' },
  fileDate: {
    fontSize: 10,
    color: '#a8a29e',
    fontFamily: 'monospace',
    minWidth: 40,
    flexShrink: 0,
    marginRight: 6,
  } as React.CSSProperties,
  fileFeature: {
    fontSize: 12,
    color: '#57534e',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  } as React.CSSProperties,
  emptySmall: { color: '#a8a29e', fontSize: 12, padding: '12px 14px' },
  docViewer: {
    flex: 1,
    overflow: 'auto' as const,
    padding: '20px 28px',
    backgroundColor: '#fff',
    minHeight: 0,
  },
  docHeader: {
    paddingBottom: 10,
    borderBottom: '1px solid #f0ebe3',
    marginBottom: 16,
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  docFileName: {
    fontSize: 12,
    color: '#a8a29e',
    fontWeight: 500,
    letterSpacing: 0.2,
  },
  docContent: {
    margin: 0,
    fontSize: 13.5,
    lineHeight: 1.7,
    color: '#2d2b28',
    whiteSpace: 'pre-wrap' as const,
    fontFamily: '"SF Mono", "Fira Code", "JetBrains Mono", monospace',
    fontWeight: 400,
  },
  emptyDoc: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
  },

  // ── 공통 ──
  phaseBar: { display: 'flex', gap: 4 },
  phaseStep: {
    flex: 1,
    textAlign: 'center' as const,
    padding: '3px 0',
    borderRadius: 6,
    fontSize: 10,
    fontWeight: 500,
    backgroundColor: '#f0ebe3',
    color: '#a8a29e',
    transition: 'all 0.15s',
  },
  phaseStepActive: { backgroundColor: '#c2703e', color: '#fff' },
  progressBg: {
    height: 4,
    backgroundColor: '#f0ebe3',
    borderRadius: 2,
    overflow: 'hidden' as const,
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#c2703e',
    borderRadius: 2,
    transition: 'width 0.3s',
  },

  // ── 생성 버튼 ──
  createBtn: {
    padding: '6px 14px',
    borderRadius: 8,
    border: '1px solid #d6d0c4',
    backgroundColor: '#fff',
    color: '#1c1917',
    cursor: 'pointer',
    fontSize: 12,
    fontWeight: 500,
  },

  // ── 모달 ──
  modalOverlay: {
    position: 'fixed' as const,
    inset: 0,
    backgroundColor: 'rgba(0,0,0,0.3)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 100,
  },
  modal: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: '24px 28px',
    width: 420,
    boxShadow: '0 20px 60px rgba(0,0,0,0.15)',
  },
  modalTitle: { margin: '0 0 20px', fontSize: 16, fontWeight: 600, color: '#1c1917' },
  fieldLabel: {
    display: 'block',
    fontSize: 11,
    fontWeight: 600,
    color: '#a8a29e',
    textTransform: 'uppercase' as const,
    letterSpacing: 0.8,
    marginBottom: 4,
    marginTop: 14,
  },
  fieldValue: {
    fontSize: 13,
    color: '#57534e',
    fontFamily: '"SF Mono", monospace',
    padding: '6px 0',
  },
  fieldHint: {
    fontSize: 11,
    color: '#a8a29e',
    fontFamily: '"SF Mono", monospace',
    marginTop: 4,
  },
  modalInput: {
    width: '100%',
    padding: '8px 12px',
    borderRadius: 8,
    border: '1px solid #d6d0c4',
    backgroundColor: '#faf7f2',
    color: '#1c1917',
    fontSize: 14,
    outline: 'none',
    boxSizing: 'border-box' as const,
  },
  modalError: { marginTop: 8, fontSize: 12, color: '#dc2626' },
  modalActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: 8,
    marginTop: 20,
  },

  // ── Ask Panel ──
  docViewerWrap: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column' as const,
    overflow: 'hidden' as const,
  },
  askPanel: {
    borderTop: '1px solid #e7e0d5',
    backgroundColor: '#faf7f2',
    display: 'flex',
    flexDirection: 'column' as const,
    maxHeight: 300,
    minHeight: 120,
  },
  askHeader: {
    padding: '8px 16px',
    fontSize: 11,
    fontWeight: 600,
    color: '#a8a29e',
    textTransform: 'uppercase' as const,
    letterSpacing: 0.8,
    borderBottom: '1px solid #e7e0d5',
  },
  askHistory: {
    flex: 1,
    overflow: 'auto' as const,
    padding: '8px 16px',
    display: 'flex',
    flexDirection: 'column-reverse' as const,
    gap: 8,
  },
  askBubbleUser: {
    alignSelf: 'flex-end',
    backgroundColor: '#c2703e',
    color: '#fff',
    padding: '6px 12px',
    borderRadius: '12px 12px 4px 12px',
    fontSize: 13,
    maxWidth: '80%',
    marginBottom: 4,
  },
  askBubbleAi: {
    alignSelf: 'flex-start',
    backgroundColor: '#fff',
    border: '1px solid #e7e0d5',
    padding: '8px 12px',
    borderRadius: '12px 12px 12px 4px',
    fontSize: 13,
    maxWidth: '90%',
  },
  askThinking: { color: '#a8a29e', fontStyle: 'italic' as const },
  askAnswer: {
    margin: 0,
    whiteSpace: 'pre-wrap' as const,
    fontFamily: 'inherit',
    fontSize: 13,
    lineHeight: 1.5,
    color: '#2d2b28',
  },
  askInputRow: {
    display: 'flex',
    gap: 6,
    padding: '8px 12px',
    borderTop: '1px solid #e7e0d5',
  },
  askInput: {
    flex: 1,
    padding: '8px 12px',
    borderRadius: 10,
    border: '1px solid #d6d0c4',
    backgroundColor: '#fff',
    color: '#1c1917',
    fontSize: 13,
    outline: 'none',
  },
  askBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    border: 'none',
    backgroundColor: '#c2703e',
    color: '#fff',
    cursor: 'pointer',
    fontSize: 16,
    fontWeight: 600,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },

  // ── Section ──
  sectionLabel: {
    margin: '0 0 14px',
    fontSize: 12,
    fontWeight: 600,
    color: '#a8a29e',
    textTransform: 'uppercase' as const,
    letterSpacing: 1,
  },
};
